### ISSUE TITLE
curl

### ISSUE THREAD

**Issue by Smellon69** [Wolf49406/ShellJector#4]
bruh I've tried compiling curl myself and I get internal curl errors, I try putting in the microsoft header files thing and then I get linker errors:

LNK2001: unresolved external symbol __imp_curl_easy_setopt
LNK2001: unresolved external symbol __imp_curl_easy_cleanup
LNK2001: unresolved external symbol __imp_curl_easy_init
LNK2001: unresolved external symbol __imp_curl_easy_perform

it's so goofy and idk how to correctly install curl

**Comment by Wolf49406** [comment]
https://vcpkg.io/en/getting-started
https://everything.curl.dev/get/windows/win-vcpkg
